# Generated by Django 3.2.9 on 2021-11-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='product',
            new_name='item',
        ),
    ]
