# Generated by Django 3.2.9 on 2021-11-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_product_invoiceitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
